### PR TITLE
Added VPC configuration options

### PR DESCRIPTION
**Pull request by moritzzimmer**
see new example and documentation for usage

### CODE REVIEW

**Comment by moritzzimmer** [comment]
test
√ example-with-cloudwatch-scheduled-event
√ example-with-dynamodb-event
√ example-with-vpc

**Comment by moritzzimmer** [comment]
seems like there is a problem when using interpolation syntax to configure subnet and security group lists

> vpc_config.0.security_group_ids: should be a list

Hardcoding string values works

**Comment by moritzzimmer** [comment]
> seems like there is a problem when using interpolation syntax to configure subnet and security group lists:
> 
> ```
> vpc_config {
>     security_group_ids = ["sg-123456"]
> 
>     // works: hard coded
>     # subnet_ids = ["subnet-123456", "subnet-1234567"]
> 
>     // fails: interpolation
>     subnet_ids = [
>       "${data.aws_cloudformation_stack.vpc.outputs["PrivateAlphaSubnetId"]}",
>       "${data.aws_cloudformation_stack.vpc.outputs["PrivateBetaSubnetId"]}",
>     ]
>   }
> ```
> 
> error message:
> 
> > vpc_config.0.subnet_ids: should be a list
> > vpc_config.0.security_group_ids: should be a list

fixed, see for https://github.com/hashicorp/terraform/issues/13103

**Comment by chgohlke** [comment]
Seems closed, but looks good.

**Pull request merged**
